-- Ensure unique index for upsert
CREATE UNIQUE INDEX IF NOT EXISTS translations_lang_key_uidx ON public.translations(language_code, translation_key);

INSERT INTO public.translations (language_code, translation_key, translation_value) VALUES
('en','groups.title','Community Groups'),('tr','groups.title','Topluluk Grupları'),
('en','groups.create','Create Group'),('tr','groups.create','Grup Oluştur'),
('en','groups.public_label','Public — Anyone can join'),('tr','groups.public_label','Açık — Herkes katılabilir'),
('en','groups.request_label','Request — Approval needed'),('tr','groups.request_label','İstekli — Onay gerekli'),
('en','groups.private_label','Private — Invite only'),('tr','groups.private_label','Özel — Sadece davet'),
('en','groups.admin','Admin'),('tr','groups.admin','Yönetici'),
('en','groups.post_to_group','Post to Group'),('tr','groups.post_to_group','Gruba Paylaş'),
('en','groups.public_short','Public'),('tr','groups.public_short','Herkese Açık'),
('en','groups.feed_tab','Feed'),('tr','groups.feed_tab','Akış'),
('en','venues.title','Venues'),('tr','venues.title','Mekanlar'),
('en','venues.add_venue','Add Venue'),('tr','venues.add_venue','Mekan Ekle'),
('en','venues.added_by','added'),('tr','venues.added_by','ekledi'),
('en','venues.reviews','Reviews'),('tr','venues.reviews','Yorumlar'),
('en','venues.no_reviews','No reviews yet. Be the first!'),('tr','venues.no_reviews','Henüz yorum yok. İlk yorumu sen yap!'),
('en','venues.hours','Business Hours'),('tr','venues.hours','Çalışma Saatleri'),
('en','events.title','Local Events'),('tr','events.title','Yerel Etkinlikler'),
('en','events.ends','Ends:'),('tr','events.ends','Bitiş:'),
('en','events.attendees','attendees'),('tr','events.attendees','katılımcı'),
('en','events.free','Free'),('tr','events.free','Ücretsiz'),
('en','events.location','Location'),('tr','events.location','Konum'),
('en','events.free_only','Free Only'),('tr','events.free_only','Ücretsiz'),
('en','events.create','Create Event'),('tr','events.create','Etkinlik Oluştur'),
('en','lost_found.title','Lost & Found'),('tr','lost_found.title','Kayıp & Bulundu'),
('en','lost_found.report_lost_btn','Report Lost'),('tr','lost_found.report_lost_btn','Kayıp Bildir'),
('en','lost_found.report_found_btn','Report Found'),('tr','lost_found.report_found_btn','Bulundu Bildir'),
('en','lost_found.lost_tab','Lost'),('tr','lost_found.lost_tab','Kayıp'),
('en','lost_found.found_tab','Found'),('tr','lost_found.found_tab','Bulundu'),
('en','classifieds.post_ad_btn','Post Ad'),('tr','classifieds.post_ad_btn','İlan Ver'),
('en','common.message','Message'),('tr','common.message','Mesaj'),
('en','common.contact','Contact'),('tr','common.contact','İletişim'),
('en','common.share','Share'),('tr','common.share','Paylaş'),
('en','common.save','Save'),('tr','common.save','Kaydet'),
('en','pets.create_post','Create Post'),('tr','pets.create_post','İlan Oluştur'),
('en','pets.friends','Friends'),('tr','pets.friends','Arkadaşlar'),
('en','pets.lost_found','Lost & Found'),('tr','pets.lost_found','Kayıp & Bulundu'),
('en','pets.shops_vets','Shops & Vets'),('tr','pets.shops_vets','Dükkanlar & Veteriner'),
('en','pets.sitting','Pet Care'),('tr','pets.sitting','Evcil Hayvan Bakımı'),
('en','pets.breed_mixed','Mixed'),('tr','pets.breed_mixed','Melez'),
('en','pets.all_breeds','All Breeds'),('tr','pets.all_breeds','Tüm Cinsler'),
('en','help.price_fixed','Fixed'),('tr','help.price_fixed','Sabit'),
('en','help.price_hourly','Hourly'),('tr','help.price_hourly','Saatlik'),
('en','help.what_to_do','What would you like to do?'),('tr','help.what_to_do','Ne yapmak istiyorsun?'),
('en','help.i_can_help','I Can Help'),('tr','help.i_can_help','Yardım Edebilirim'),
('en','help.i_need_help','I Need Help'),('tr','help.i_need_help','Yardıma İhtiyacım Var'),
('en','weekday.monday','Monday'),('tr','weekday.monday','Pazartesi'),
('en','weekday.tuesday','Tuesday'),('tr','weekday.tuesday','Salı'),
('en','weekday.wednesday','Wednesday'),('tr','weekday.wednesday','Çarşamba'),
('en','weekday.thursday','Thursday'),('tr','weekday.thursday','Perşembe'),
('en','weekday.friday','Friday'),('tr','weekday.friday','Cuma'),
('en','weekday.saturday','Saturday'),('tr','weekday.saturday','Cumartesi'),
('en','weekday.sunday','Sunday'),('tr','weekday.sunday','Pazar')
ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value, updated_at = now();